set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_VERSION 1)

if(NOT DEFINED ENV{WIN32_INSTALL_PREFIX} AND DEFINED ENV{SYSROOT})
  set(ENV{WIN32_INSTALL_PREFIX} "$ENV{SYSROOT}/usr")
endif()

# Root
if(DEFINED ENV{WIN32_INSTALL_PREFIX})
  set(WIN32_INSTALL_PREFIX "$ENV{WIN32_INSTALL_PREFIX}")
  string(REPLACE "\\" "/" WIN32_INSTALL_PREFIX "${WIN32_INSTALL_PREFIX}")
  set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
  list(PREPEND CMAKE_FIND_ROOT_PATH "${WIN32_INSTALL_PREFIX}")
  list(PREPEND CMAKE_PREFIX_PATH "${WIN32_INSTALL_PREFIX}")
  list(PREPEND _pkg_config "${WIN32_INSTALL_PREFIX}/lib/pkgconfig")
  set(CMAKE_INSTALL_PREFIX
      "${WIN32_INSTALL_PREFIX}"
      CACHE PATH "Install path"
  )
  set(CMAKE_C_FLAGS "-I${WIN32_INSTALL_PREFIX}/include ${CMAKE_C_FLAGS}")
  set(CMAKE_CXX_FLAGS "-I${WIN32_INSTALL_PREFIX}/include ${CMAKE_CXX_FLAGS}")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /EHsc")
  link_directories("${WIN32_INSTALL_PREFIX}/lib")
  list(FIND CMAKE_FIND_ROOT_PATH "${CMAKE_INSTALL_PREFIX}" _find_index)
  if(_find_index EQUAL -1 AND NOT "${CMAKE_INSTALL_PREFIX}" STREQUAL "${WIN32_INSTALL_PREFIX}")
    list(PREPEND CMAKE_FIND_ROOT_PATH "${CMAKE_INSTALL_PREFIX}")
    list(PREPEND _pkg_config "${CMAKE_INSTALL_PREFIX}/lib/pkgconfig")
  endif()
endif()
if(DEFINED ENV{PKG_CONFIG_PATH} AND NOT "$ENV{PKG_CONFIG_PATH}" STREQUAL "")
  set(ENV{PKG_CONFIG_PATH} "$ENV{PKG_CONFIG_PATH};${_pkg_config}")
else()
  set(ENV{PKG_CONFIG_PATH} "${_pkg_config}")
endif()
unset(_find_index)
unset(_pkg_config)

# Flags
if(DEFINED ENV{CFLAGS})
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} $ENV{CFLAGS}")
endif()

if(DEFINED ENV{CXXFLAGS})
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} $ENV{CXXFLAGS}")
endif()

add_compile_options(/wd4068 /wd4158 /wd4819 /wd5287)
add_compile_options(/GL)
add_link_options(/LTCG)
add_link_options(/IGNORE:4078)
