if(DEFINED ENV{OE_CMAKE_TOOLCHAIN_FILE})
  include($ENV{OE_CMAKE_TOOLCHAIN_FILE})
endif()

set(CMAKE_SYSTEM_PROCESSOR AMD64)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_CROSSCOMPILING FALSE)

include(${CMAKE_CURRENT_LIST_DIR}/win32.toolchain.common.cmake)
