if(VKIT_TOOLCHAIN_LOADED)
  return()
endif()

# cmake settings
set(VKIT_TOOLCHAIN_LOADED TRUE)
set(CMAKE_INSTALL_MESSAGE LAZY)
set(CMAKE_RULE_MESSAGES FALSE)

# check
if(NOT DEFINED ENV{VKIT_ROOT_DIR})
  message(FATAL_ERROR "The 'VKIT_ROOT_DIR' environment variable is not set")
endif()

if(NOT DEFINED ENV{VKIT_PLATFORM})
  message(FATAL_ERROR "The 'VKIT_PLATFORM' environment variable is not set")
endif()

if(NOT DEFINED ENV{VKIT_PREBUILT_DIR})
  message(FATAL_ERROR "The 'VKIT_PREBUILT_DIR' environment variable is not set")
endif()

# find cmake-toolchain
if("$ENV{VKIT_PLATFORM}" STREQUAL "qnx-aarch64")
  set(ENV{QNX_INSTALL_PREFIX} "$ENV{VKIT_PREBUILT_DIR}")
  set(VKIT_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/qnx/qnx.toolchain.aarch64.cmake)
elseif("$ENV{VKIT_PLATFORM}" STREQUAL "qnx-x86_64")
  set(ENV{QNX_INSTALL_PREFIX} "$ENV{VKIT_PREBUILT_DIR}")
  set(VKIT_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/qnx/qnx.toolchain.x86_64.cmake)
elseif("$ENV{VKIT_PLATFORM}" STREQUAL "android-aarch64")
  set(ENV{ANDROID_INSTALL_PREFIX} "$ENV{VKIT_PREBUILT_DIR}")
  set(VKIT_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/android/android.toolchain.aarch64.cmake)
elseif("$ENV{VKIT_PLATFORM}" STREQUAL "android-x86_64")
  set(ENV{ANDROID_INSTALL_PREFIX} "$ENV{VKIT_PREBUILT_DIR}")
  set(VKIT_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/android/android.toolchain.x86_64.cmake)
elseif("$ENV{VKIT_PLATFORM}" STREQUAL "linux-aarch64")
  set(ENV{LINUX_INSTALL_PREFIX} "$ENV{VKIT_PREBUILT_DIR}")
  set(VKIT_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/linux/linux.toolchain.aarch64.cmake)
elseif("$ENV{VKIT_PLATFORM}" STREQUAL "linux-x86_64")
  set(ENV{LINUX_INSTALL_PREFIX} "$ENV{VKIT_PREBUILT_DIR}")
  set(VKIT_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/linux/linux.toolchain.x86_64.cmake)
elseif("$ENV{VKIT_PLATFORM}" STREQUAL "freebsd-aarch64")
  set(ENV{LINUX_INSTALL_PREFIX} "$ENV{VKIT_PREBUILT_DIR}")
  set(VKIT_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/linux/linux.toolchain.aarch64.cmake)
elseif("$ENV{VKIT_PLATFORM}" STREQUAL "freebsd-x86_64" OR "$ENV{VKIT_PLATFORM}" STREQUAL "freebsd-amd64")
  set(ENV{LINUX_INSTALL_PREFIX} "$ENV{VKIT_PREBUILT_DIR}")
  set(VKIT_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/linux/linux.toolchain.x86_64.cmake)
elseif("$ENV{VKIT_PLATFORM}" STREQUAL "darwin-aarch64" OR "$ENV{VKIT_PLATFORM}" STREQUAL "darwin-arm64")
  set(ENV{DARWIN_INSTALL_PREFIX} "$ENV{VKIT_PREBUILT_DIR}")
  set(VKIT_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/darwin/darwin.toolchain.aarch64.cmake)
elseif("$ENV{VKIT_PLATFORM}" STREQUAL "darwin-x86_64")
  set(ENV{DARWIN_INSTALL_PREFIX} "$ENV{VKIT_PREBUILT_DIR}")
  set(VKIT_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/darwin/darwin.toolchain.x86_64.cmake)
elseif("$ENV{VKIT_PLATFORM}" STREQUAL "win32-x86_64")
  set(ENV{WIN32_INSTALL_PREFIX} "$ENV{VKIT_PREBUILT_DIR}")
  set(VKIT_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/win32/win32.toolchain.x86_64.cmake)
else()
  message(FATAL_ERROR "Unknown platform [$ENV{VKIT_PLATFORM}]!")
endif()

# set cmake-toolchains
message(STATUS "VKit platform: $ENV{VKIT_PLATFORM}")
message(STATUS "VKit device:   $ENV{VKIT_DEVICE}")
include(${VKIT_TOOLCHAIN_FILE})

# set build_type and install_prefix
if(NOT DEFINED CMAKE_BUILD_TYPE)
  if("$ENV{VKIT_DEBUG}" STREQUAL "1")
    set(CMAKE_BUILD_TYPE "Debug")
  else()
    set(CMAKE_BUILD_TYPE "Release")
  endif()
endif()
set(CMAKE_INSTALL_PREFIX "$ENV{VKIT_PREBUILT_DIR}" CACHE PATH "Install path" FORCE)

if(EXISTS "${CMAKE_INSTALL_PREFIX}/include/boost")
  set(Boost_NO_SYSTEM_PATHS ON)
  set(BOOST_ROOT ${CMAKE_INSTALL_PREFIX})
endif()

# support prebuilt-ext
if(DEFINED ENV{VKIT_PREBUILT_EXT_DIR})
  set(VKIT_INSTALL_PREFIX_EXT "$ENV{VKIT_PREBUILT_EXT_DIR}")
  if(WIN32)
    string(REPLACE "\\" "/" VKIT_INSTALL_PREFIX_EXT "${VKIT_INSTALL_PREFIX_EXT}")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -I${VKIT_INSTALL_PREFIX_EXT}/include")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -I${VKIT_INSTALL_PREFIX_EXT}/include")
    link_directories("${VKIT_INSTALL_PREFIX_EXT}/lib")
    list(PREPEND CMAKE_PREFIX_PATH "${VKIT_INSTALL_PREFIX_EXT}")
  else()
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -I${VKIT_INSTALL_PREFIX_EXT}/include -L${VKIT_INSTALL_PREFIX_EXT}/lib")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -I${VKIT_INSTALL_PREFIX_EXT}/include -L${VKIT_INSTALL_PREFIX_EXT}/lib")
  endif()
  list(APPEND CMAKE_FIND_ROOT_PATH "${VKIT_INSTALL_PREFIX_EXT}")
  set(ENV{PKG_CONFIG_PATH} "$ENV{PKG_CONFIG_PATH}:${VKIT_INSTALL_PREFIX_EXT}/lib/pkgconfig")
  if(ENABLE_INSTALL_PREFIX_EXT)
    set(CMAKE_INSTALL_PREFIX "${VKIT_INSTALL_PREFIX_EXT}" CACHE PATH "Install path" FORCE)
  endif()
endif()

# skip warning
if(POLICY CMP0011)
  cmake_policy(SET CMP0011 NEW)
endif()
if(POLICY CMP0144)
  cmake_policy(SET CMP0144 OLD)
endif()
if(POLICY CMP0148)
  cmake_policy(SET CMP0148 OLD)
endif()
if(POLICY CMP0167)
  cmake_policy(SET CMP0167 OLD)
endif()
if(POLICY CMP0177)
  cmake_policy(SET CMP0177 OLD)
endif()
if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR CMAKE_CXX_COMPILER MATCHES "clang" OR CMAKE_CXX_CLANG_TIDY OR CMAKE_ANDROID_NDK)
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-unused-command-line-argument")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-unused-command-line-argument")
  if(CMAKE_CXX_CLANG_TIDY)
    message(STATUS "Using [clang-tidy] for code checking...")
  endif()
endif()

# ccache
if(NOT WIN32 AND NOT QNX AND NOT CMAKE_CXX_CLANG_TIDY AND NOT "$ENV{VKIT_DISABLE_CCACHE}" STREQUAL "1")
  if(NOT DEFINED CCACHE_FOUND)
    find_program(CCACHE_FOUND ccache)
  endif()
  if(CCACHE_FOUND)
    message(STATUS "Use [ccache] for build...")
    set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
    set_property(GLOBAL PROPERTY RULE_LAUNCH_LINK ccache)
  endif()
endif()

# uninstall
if(NOT TARGET __uninstall)
  configure_file(
    "${CMAKE_CURRENT_LIST_DIR}/uninstall.cmake.in"
    "${CMAKE_BINARY_DIR}/__uninstall.cmake"
    @ONLY
  )
  add_custom_target(__uninstall
    COMMAND ${CMAKE_COMMAND} -P ${CMAKE_BINARY_DIR}/__uninstall.cmake
    COMMENT "Uninstalling files listed in install_manifest.txt ..."
  )
endif()
